# Indian States 

ANDHRA_PRADESH: str = "ANDHRA_PRADESH"
ARUNACHAL_PRADESH: str = "ARUNACHAL_PRADESH"
ASSAM: str = "ASSAM"
BIHAR: str = "BIHAR"
CHHATTISGARH: str = "CHHATTISGARH"
GOA: str = "GOA"
GUJARAT: str = "GUJARAT"
HARYANA: str = "HARYANA"
HIMACHAL_PRADESH: str = "HIMACHAL_PRADESH"
JHARKHAND: str = "JHARKHAND"
KARNATAKA: str = "KARNATAKA"
KERALA: str = "KERALA"
MADHYA_PRADESH: str = "MADHYA_PRADESH"
MAHARASHTRA: str = "MAHARASHTRA"
MANIPUR: str = "MANIPUR"
MEGHALAYA: str = "MEGHALAYA"
MIZORAM: str = "MIZORAM"
NAGALAND: str = "NAGALAND"
ODISHA: str = "ODISHA"
PUNJAB: str = "PUNJAB"
RAJASTHAN: str = "RAJASTHAN"
SIKKIM: str = "SIKKIM"
TAMIL_NADU: str = "TAMIL_NADU"
TELANGANA: str = "TELANGANA"
TRIPURA: str = "TRIPURA"
UTTAR_PRADESH: str = "UTTAR_PRADESH"
UTTARAKHAND: str = "UTTARAKHAND"
WEST_BENGAL: str = "WEST_BENGAL"

ALL_STATES = (
    ANDHRA_PRADESH,
    ARUNACHAL_PRADESH,
    ASSAM,
    BIHAR,
    CHHATTISGARH,
    GOA,
    GUJARAT,
    HARYANA,
    HIMACHAL_PRADESH,
    JHARKHAND,
    KARNATAKA,
    KERALA,
    MADHYA_PRADESH,
    MAHARASHTRA,
    MANIPUR,
    MEGHALAYA,
    MIZORAM,
    NAGALAND,
    ODISHA,
    PUNJAB,
    RAJASTHAN,
    SIKKIM,
    TAMIL_NADU,
    TELANGANA,
    TRIPURA,
    UTTAR_PRADESH,
    UTTARAKHAND,
    WEST_BENGAL,
)